### ISSUE TITLE
User Settings screen

### ISSUE THREAD

**Issue by StarlingZen** [dibley1973/the-train-exchange#27]
**As a** signed in user
**I want to** have a settings screen
**so that** i can make changes to my account

**it is acceptable when...**

- a screen exists that shows me all settings for my account as a user
- options are available for changing my password, my email address, deleting my account or updating any other information it is decided the site will store
- the user is prompted to re-enter their password when making changes even if already signed in

**Comment by dibley1973** [comment]
A quick question. What is the difference between this and issue #11?

**Comment by StarlingZen** [comment]
Duplicate
